### ISSUE TITLE
some environment / config variable is missing when working without proxy

### ISSUE THREAD

**Issue by joergmschulz** [tiredofit/docker-zabbix#3]
Using the :latest (3.1.6) version.
Most of the functionality is working, hosts are detected, graphs are displayed. 
But, in the top left corner, Zabbix is complaining that the zabbix server itself cannit be found (keyword: Unable to connect to :10051 )

<img width="434" alt="image" src="https://user-images.githubusercontent.com/6523646/155335878-316df7f0-e9d4-4307-8be9-5cf785ee5b01.png">

`fsockopen(): php_network_getaddresses: getaddrinfo failed: Name does not resolve [zabbix.php:22 → require_once() → ZBase->run() → ZBase->processRequest() → CController->run() → CControllerWidgetSystemInfoView->doAction() → CSystemInfoHelper::getData() → CSystemInfoHelper::getServerStatus() → CZabbixServer->isRunning() → CZabbixServer->request() → CZabbixServer->connect() → fsockopen() in include/classes/server/CZabbixServer.php:594]
fsockopen(): Unable to connect to :10051 (php_network_getaddresses: getaddrinfo failed: Name does not resolve) [zabbix.php:22 → require_once() → ZBase->run() → ZBase->processRequest() → CController->run() → CControllerWidgetSystemInfoView->doAction() → `

scrolling through the output in DEBUG mode didn't reveal much promising output.
Maybe I'm missing one important environment variable?

extract of my docker-compose.yml:
```environment:
        - DB_HOST=postgres-db
        - DB_PORT=5432
        - POSTGRES_USER=zabbix
        - "POSTGRES_PASSWORD=superpassword"
        - DB_NAME=zabbix
        - ZBX_DBSCHEMA=public
        - ZABBIX_MODE=SERVER
        - DB_SCHEMA=public
        - DB_USER=zabbix
        - "DB_PASS=superpassword"
        - ZABBIX_SERVER_ACTIVE=zabbix-server
        - ZABBIX_SERVER_HOSTNAME=zabbix-server
        - ZBX_SERVER_HOST=zabbix-server
          # - DEBUG_MODE=true
        - TIMEZONE=Europe/Berlin
        - SMTP_DEBUG=0
        - SMTP_HOST=m.${DOMAIN}.de```

**Comment by tiredofit** [comment]
Hi, This is highly undocumented and I apologize, Let me give a fuzzed version of a known working docker-compose.yml and see if this can help you.

I assume you've tried to login to the "server" compoent and both the "web" component and tried to resolve the container_names ?

This has been working fine. It was glitchy when I first updated to version 6.0. I had to follow the 6.0 upgrade steps for Zabbix as my history was all messed up from the upgrade from 5.4. It's been very reliable for a week now with half a dozen proxies, some servers, and monitoring a couple thousand hosts.

````
version: '2.4'
services:
    
    monitor-example-com-server:
      image: tiredofit/zabbix:latest
      container_name: monitor-example-com-server
      dns:
        - 172.19.128.53
      ports:
        - 172.XX.0.XX:10051:10051
      volumes:
        - ./assets/externalscripts:/assets/externalscripts
        - ./assets/alertscripts:/assets/alertscripts
        - ./data/var/lib/zabbix/modules:/var/lib/zabbix/modules
        - ./data/var/lib/zabbix/enc:/var/lib/zabbix/enc
        - ./data/var/lib/zabbix/ssh_keys:/var/lib/zabbix/ssh_keys
        - ./data/var/lib/zabbix/mibs:/var/lib/zabbix/mibs
        - ./logs/server:/var/log/zabbix/server
      links:
        - monitor-example-com-db
      ulimits:
        nproc: 65535
        nofile:
          soft: 20000
          hard: 40000
      environment:
        - TIMEZONE=America/Vancouver
        - CONTAINER_NAME=monitor-example-com-server
        - CONTAINER_ENABLE_LOGSHIPPING=FALSE

        - ZABBIX_MODE=SERVER
        - ZABBIX_SERVER_CACHE_SIZE=48M
        - ZABBIX_SERVER_CACHE_HISTORY_INDEX=32M
        - ZABBIX_SERVER_CACHE_HISTORY_SIZE=32M
        - ZABBIX_SERVER_CACHE_VALUE_SIZE=32M
        - ZABBIX_SERVER_CACHE_TREND_FUNCTION_SIZE=32M
        - ZABBIX_SERVER_START_DISCOVERER=3
        - ZABBIX_SERVER_START_PINGERS=5
        - ZABBIX_SERVER_START_PROXY_POLLERS=8
        - ZABBIX_SERVER_START_ESCALATORS=3
        - ZABBIX_SERVER_START_TIMERS=3
        - ZABBIX_SERVER_START_ALERTERS=5
        - ZABBIX_SERVER_WEBSERVICE_URL=http://monitor-example-com-webservice:10053/report
        - DB_HOST=monitor-example-com-db
        - DB_PORT=5432
        - DB_NAME=zabbix
        - DB_PASS=zabbix
        - DB_USER=zabbix
        - DB_SCHEMA=public
      networks:
        services:
          aliases:
            - monitor-server
      restart: always

    monitor-example-com-app:
      image: tiredofit/zabbix:latest
      container_name: monitor-example-com-app
      #mem_limit: 512m
      volumes:
        - ./logs/nginx:/www/logs/nginx
        - ./certs:/www/zabbix/conf/certs
      links:
        - monitor-example-com-db
        - monitor-example-com-server
      labels:
        - traefik.enable=true
        - traefik.http.routers.monitor-example-com.rule=Host(`monitor.example.com`)
        - traefik.http.services.monitor-example-com.loadbalancer.server.port=80
      environment:
        - TIMEZONE=America/Vancouver
        - ZABBIX_MODE=WEB
        - CONTAINER_NAME=monitor-example-com-app
        - CONTAINER_ENABLE_LOGSHIPPING=FALSE

        - ZABBIX_SERVER_HOST=monitor-example-com-server
        - ZABBIX_SERVER_PORT=10051
        - ZABBIX_SERVER_NAME=monitor.example.com

        - PHP_TIMEOUT=600
        - PHP_MEMORY_LIMIT=512M
        - DB_HOST=monitor-example-com-db
        - DB_PORT=5432
        - DB_USER=zabbix
        - DB_PASS=zabbix
        - DB_NAME=zabbix
        - DB_SCHEMA=public

        - SSO_SETTINGS='use_proxy_headers' => true
      networks:
        - proxy
        - services
      restart: always

    monitor-example-com-webservice:
      image: tiredofit/zabbix:latest
      container_name: monitor-example-com-webservice
      #mem_limit: 512m
      cap_add:
        - SYS_ADMIN
      volumes:
        - ./logs/webservice:/var/log/zabbix/webservice
        - ./certs:/www/zabbix/conf/certs
      links:
        - monitor-example-com-db
        - monitor-example-com-server
      environment:
        - TIMEZONE=America/Vancouver
        - ZABBIX_MODE=WEBSERVICE
        - CONTAINER_NAME=monitor-example-com-webservice
        - CONTAINER_ENABLE_LOGSHIPPING=TRUE
      networks:
        - services
      restart: always
      
    monitor-example-com-db:
      image: tiredofit/postgres:14-latest
      container_name: monitor-example-com-db
      user: root
      volumes:
        - /var/local/db/monitor.example.com:/var/lib/postgresql/data
      environment:
        - CONTAINER_NAME=monitor-example-com-db
        - CONTAINER_ENABLE_LOGSHIPPING=TRUE
        - CONTAINER_ENABLE_MONITORING=TRUE
        - TIMEZONE=America/Vancouver
        - POSTGRES_USER=zabbix
        - POSTGRES_PASSWORD=zabbix
        - POSTGRES_DB=zabbix
        - ZABBIX_SERVER=172.16.0.0/12
        - ZABBIX_SERVER_ACTIVE=monitor-example-com-server
      networks:
        services:
          aliases:
            - monitor-db
      restart: always

    monitor-example-com-db-backup:
      image: tiredofit/db-backup
      container_name: monitor-example-com-db-backup
      links:
        - monitor-example-com-db
      volumes:
        - /mnt/data/data/monitor.example.com/dbbackup:/backup
      environment:
        - TIMEZONE=America/Vancouver
        - CONTAINER_NAME=monitor-example-com-db-backup
        - CONTAINER_ENABLE_LOGSHIPPING=TRUE

        - ZABBIX_SERVER=172.16.0.0/12
        - ZABBIX_SERVER_ACTIVE=monitor-example-com-server
        - DB_HOST=monitor-example-com-db
        - DB_TYPE=postgres
        - DB_NAME=zabbix
        - DB_USER=zabbix
        - DB_PASS=zabbix
        - DB_DUMP_FREQ=1440
        - DB_DUMP_BEGIN=0130
        - DB_CLEANUP_TIME=4320
      networks:        
        - services
      restart: always
````
